apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: rhel9-marked-peacock
  namespace: lamp-virt
  labels:
    app: rhel9-marked-peacock
    vm.kubevirt.io/template: rhel9-server-small
    vm.kubevirt.io/template.namespace: openshift
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.23.5
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        creationTimestamp: null
        name: rhel9-marked-peacock
      spec:
        sourceRef:
          kind: DataSource
          name: rhel9
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
  running: false
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: rhel9
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: rhel9-marked-peacock
        kubevirt.io/size: small
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - bridge: {}
              model: virtio
              name: nic-1085
          networkInterfaceMultiqueue: true
          rng: {}
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: pc-q35-rhel8.6.0
        resources:
          requests:
            memory: 2Gi
      evictionStrategy: LiveMigrate
      networks:
        - multus:
            networkName: nad-1085
          name: nic-1085
      terminationGracePeriodSeconds: 180
      volumes:
        - dataVolume:
            name: rhel9-marked-peacock
          name: rootdisk
        - cloudInitNoCloud:             
            userData: |
              #cloud-config
              user: XXXX
              password: XXXX          
              chpasswd:
                expire: false
              runcmd: 
                - sudo localectl set-keymap fr         
          name: cloudinitdisk
